language: cpp
dist: bionic 

before_script:
  - mkdir build
  - cd build

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-9
      script:
        - cmake .. -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9
        - make

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
            - libstdc++-8-dev
      script:
        - cmake .. -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8
        - make
